spring.data.mongodb:
  host: localhost
  port: 27023
  database: orders

---
spring:
  profiles: local
  data.mongodb:
      host: localhost
      port: 27023
      database: orders
      username:
      password:

---
spring:
  profiles: test
  data.mongodb:
    host: localhost
    port: 27023
    database: orders
    username:
    password:
